---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download simple web site 
  hosts: all 

  gather_facts: false
  tasks:
    - name: Download simple web site to 'Ansible Template'
      template:
        src: templates/index.html.j2
        dest: 'C:/inetpub/wwwroot/index.html'
