---
- name: installIISServer
  hosts: all
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: True
        include_management_tools: True
      register: output
    - name: reboot if installing Web-Server feature requires it
      win_reboot:
      when: output.reboot_required
